// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4ABMJBo3BHl-unlxS4Jx-lIs-3ZkQBK8',
    appId: '1:637218275668:web:209bfdd79fd50f0c0108c1',
    messagingSenderId: '637218275668',
    projectId: 'pas-ecommerce',
    authDomain: 'pas-ecommerce.firebaseapp.com',
    storageBucket: 'pas-ecommerce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoaU1djZBymlcZrsrMihU8SBSOehwabHY',
    appId: '1:637218275668:android:6b5c44b0e1b562ad0108c1',
    messagingSenderId: '637218275668',
    projectId: 'pas-ecommerce',
    storageBucket: 'pas-ecommerce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA3W9VCFJyW67UngoBTwjidnKz7H8UdUc',
    appId: '1:637218275668:ios:0b96bf08b1b57e330108c1',
    messagingSenderId: '637218275668',
    projectId: 'pas-ecommerce',
    storageBucket: 'pas-ecommerce.appspot.com',
    androidClientId: '637218275668-6f2sflumvie83dpojbvu3vpns6mh9qp1.apps.googleusercontent.com',
    iosClientId: '637218275668-oobo02v85nsr5ruefnk926gujr43bv8k.apps.googleusercontent.com',
    iosBundleId: 'com.example.pasKelas11',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA3W9VCFJyW67UngoBTwjidnKz7H8UdUc',
    appId: '1:637218275668:ios:ce6289c970ce5afe0108c1',
    messagingSenderId: '637218275668',
    projectId: 'pas-ecommerce',
    storageBucket: 'pas-ecommerce.appspot.com',
    androidClientId: '637218275668-6f2sflumvie83dpojbvu3vpns6mh9qp1.apps.googleusercontent.com',
    iosClientId: '637218275668-usarhjnuko3idjo24eqqu8k6sof1k7kj.apps.googleusercontent.com',
    iosBundleId: 'com.example.pasKelas11.RunnerTests',
  );
}
